return {
  -- "rose-pine/neovim",
  -- name = "rose-pine",
  -- lazy = false,
  -- priority = 1000,
  -- opts = {
  --   variant = "moon",
  --   dark_variant = "main",
  --   styles = {
  --     bold = true,
  --     italic = true,
  --     transparency = false,
  --   },
  --
  --   palette = {
  --     moon = {
  --       -- THE NIGHT OWL FOUNDATION
  --       base = "#011627",
  --       surface = "#011f35",
  --       overlay = "#0b2942",
  --
  --       -- TOKYO NIGHT MAGENTA & BLUE INJECTION
  --       iris = "#bb9af7", -- Tokyo Night Magenta (Functions)
  --       subtle = "#7aa2f7", -- Tokyo Night Blue (Punctuation/Operators)
  --       foam = "#2ac3de", -- Tokyo Night Cyan (Variables/Members)
  --       leaf = "#9ece6a", -- Tokyo Night Green (Strings)
  --
  --       -- ROSÉ PINE VIBE
  --       rose = "#ff7eb6", -- Rosé Keyword Pink
  --       love = "#f7768e", -- Tokyo Night Red/Pink (Errors)
  --       gold = "#e0af68", -- Tokyo Night Orange/Gold (Types)
  --
  --       muted = "#565f89", -- Tokyo Night Dark Gray (Comments)
  --       text = "#cfc9c2", -- Slightly warmer text for eye comfort
  --     },
  --   },
  --
  --   highlight_groups = {
  --     -- 1. TOKYO NIGHT SYNTAX LOGIC
  --     ["@keyword"] = { fg = "rose" },
  --     ["@keyword.modifier"] = { fg = "rose", italic = true },
  --
  --     -- Using the Tokyo Magenta for Functions
  --     ["@function"] = { fg = "iris" },
  --     ["@method"] = { fg = "iris" },
  --     ["@function.call"] = { fg = "iris" },
  --
  --     -- The Tokyo Cyan "Glow" for data members
  --     ["@variable.member"] = { fg = "foam" },
  --     ["@property"] = { fg = "foam" },
  --     ["@parameter"] = { fg = "foam", italic = true },
  --
  --     -- Tokyo Blue for "Code Hardware" (Brackets, Operators)
  --     ["@punctuation.bracket"] = { fg = "subtle" },
  --     ["@operator"] = { fg = "subtle" },
  --
  --     -- 2. THE COMMENT FIX (Tokyo Night Storm style)
  --     ["Comment"] = { fg = "muted", italic = true },
  --     ["@comment"] = { fg = "muted", italic = true },
  --
  --     -- 3. UI ACCENTS
  --     Visual = { bg = "#283457", inherit = false }, -- Tokyo Night Visual Selection
  --     CursorLine = { bg = "#021320" },
  --     Search = { bg = "#3d59a1", fg = "#ffffff" }, -- Tokyo Night Deep Blue Search
  --   },
  -- },
  -- config = function(_, opts)
  --   require("rose-pine").setup(opts)
  --   vim.cmd("colorscheme rose-pine-moon")
  -- end,
}
